<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>AnyCPU;x86</Platforms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyTitle>PaveMetric</AssemblyTitle>
    <Product>PaveMetric</Product>
    <Copyright>Copyright © 2012</Copyright>
  </PropertyGroup>

</Project>
